resources:
  - name: concourse-php
    type: git
    source:
      repository: git@github.com:mpfmedical/concourse-php
      private_key: {{GITHUB_PRIVATE_KEY}}
  - name: image
    type: docker-image
    source:
      repository: mpfmedical/concourse-php
      username: {{HUB_USERNAME}}
      password: {{HUB_PASSWORD}}
jobs:
  - name: build
    plan:
      - get: concourse-php
        trigger: true
      - put: image
        params:
          build: concourse-php
